baseurl: "/Handbuch-Jugend-Hackathons"

collections:
    - chapters

collections:
    chapters:
        output: false
        permalink: /chapters/:path/


defaults:
  - scope:
        path: ""
        type: chapters