baseurl: "/Handbuch-Jugend-Hackathons"

collections:
    - chapters

collections:
    chapters:
        output: true
        permalink: /chapters/:path/


defaults:
  - scope:
      path: ""
      type: chapters
    values:
      layout: chapter