baseurl: "/Handbuch-Jugend-Hackathons"

collections:
    - 01_Vorwort
    - 02_Einleitung
    - 03_Phasen 

collections:
    chapters:
        output: true
        permalink: /chapters/:path/

defaults:
  - scope:
        path: ""
        type: chapters
    values:
        layout: chapter